title: SOEUNG Phearaeron
email: phearaneron.soeung@gmail.com
description: >-
  Personal website of Neron
baseurl: "/pr0meth4us"
url: "https://pr0meth4us.github.io"

navigation:
  - text: "Home"
    url: "/"
    primary: true
  - text: "About Me"
    url: "/about"
    primary: false
  - text: "Coding Projects"
    url: "/projects"
    primary: false
  - text: "Papers"
    url: "/papers"
    primary: false
  - text: "Others"
    url: "/misc"
    primary: false

contact_info:
  - type: "email"
    url: "mailto:phearaneron.soeung@gmail.com"
  - type: "phone"
    text: "+855 962021314"
    url: "tel:+855962021314"
  - type: "github"
    text: "github.com/pr0meth4us"
    url: "https://github.com/pr0meth4us"
  - type: "linkedin"
    text: "linkedin.com/in/nernnnnnnn/"
    url: "https://linkedin.com/in/nernnnnnnn/"
  - type: "telegram"
    text: "https://t.me/nernnnnnnn"
    url: "https://t.me/nernnnnnnn"

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/