title: SOEUNG Phearaeron
email: phearaneron.soeung@gmail.com
description: >-
  Personal website of Neron
baseurl: "/pr0meth4us"
url: "https://pr0meth4us.github.io/"

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/