title: SOEUNG Phearaeron
email: your-email@example.com
description: >-
  Personal website of SOEUNG Phearaeron, blending IT and International Relations 
  to shape Cambodia's digital future.
baseurl: ""
url: ""

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/